### ISSUE TITLE
Browsh sees wrong version of Firefox

### ISSUE THREAD

**Issue by Celofyz** [browsh-org/browsh#203]
Windows 10 x64 build 16299
Firefox 62 x64
Error: Installed Firefox version 54.0.1 is too old. Firefox 57 or newer is needed

I don's have installed any other versions than 62, so I can't have 54. Also i pointed directly to FF executable using --firefox.path but it didn't help.

**Comment by tombh** [comment]
Sometimes passing the path can be problematic if there are spaces in it. Maybe spaces are making it fallback to the older version. Might be worth running `browsh --debug` and posting the logs.

**Comment by Celofyz** [comment]
Debug.log file was not created so I'm posting error from cmd:

C:\Program Files\Mozilla Firefox>browsh --debug
Logging to: C:\Program Files\Mozilla Firefox\debug.log
panic: interface conversion: error is *os.PathError, not *errors.Error

goroutine 1 [running]:
browsh/interfacer/src/browsh.Shutdown(0x9ae480, 0xc042182960)
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:95 +0x184
browsh/interfacer/src/browsh.Log(0xc04207e460, 0x4a)
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:70 +0x17f
browsh/interfacer/src/browsh.loadConfig()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/config.go:80 +0x115
browsh/interfacer/src/browsh.Initialise()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:89 +0x4a
browsh/interfacer/src/browsh.MainEntry()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:194 +0x32
main.main()
        /home/travis/gopath/src/browsh/interfacer/src/main.go:6 +0x27


I moved Browsh with Firefox to different directory. It still says I have Firefox 54, but now it created debug.log, I'm attaching it to the post.
[debug.log](https://github.com/browsh-org/browsh/files/2408342/debug.log)

I see in log that Browsh reads Firefox version from the register. I searched it for version key and, to my surprise, I've found a lot of keys with different versions.
[FirefoxVersionRegisterPathsFound.txt](https://github.com/browsh-org/browsh/files/2408353/FirefoxVersionRegisterPathsFound.txt)

I tried to change the first key from listed in txt above "54.0.1" to "62.0"
Now it crashed with different error, but it opened new firefox window.
cmd: C:\Browsh>browsh --firefox.path C:\Browsh\firefox.exe --debug
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4cc53d]
[debug.log](https://github.com/browsh-org/browsh/files/2408358/debug.log)
