### ISSUE TITLE
segmentation fault on ubuntu server 16.04

### ISSUE THREAD

**Issue by nightpool** [browsh-org/browsh#274]
Installed browsh onto my digitalocean server using the instructions at https://www.brow.sh/docs/installation/ and after installation it won't start up at all:

```
root@nightpool:~# browsh --http-server-mode --debug
Logging to: /root/debug.log
Waiting for Firefox to connect...
Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Using Firefox at: /usr/bin/firefox
Using default profile at: /root/.config/browsh/firefox_profile
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4bf5ce]

goroutine 6 [running]:
os.(*Process).signal(0x0, 0x9af5c0, 0xbd35b8, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0x9af5c0, 0xbd35b8, 0xc42006de80, 0x18)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/os/exec.go:129 +0x3f
os.(*Process).kill(0x0, 0xc4200019a8, 0xc42006de80)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/os/exec_posix.go:54 +0x43
os.(*Process).Kill(0x0, 0x4, 0x4)
        /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/os/exec.go:114 +0x2b
browsh/interfacer/src/browsh.startHeadlessFirefox()
        /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:86 +0x3b2
created by browsh/interfacer/src/browsh.setupFirefox
        /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:299 +0x35   
```

debug.log:
```
Looking in /root/.config/browsh/config.toml for config.
```

Firefox seems to be installed:

```
root@nightpool:~# firefox -v
Mozilla Firefox 68.0
```

**Comment by tombh** [comment]
What happens if you run `firefox --headless` on its own?

**Comment by tombh** [comment]
Closing due to inactivity. Please feel free to reopen.

**Comment by alexpyattaev** [comment]
Same bug reappeared on my ubuntu machines. Firefox headless starts reporting a couple of non-critical issues:
```
firefox --headless
/usr/bin/firefox: 12: xdg-settings: not found
*** You are running in headless mode.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt

```
Not sure how critical this is. Any help would be appreciated.

**Comment by rogercloud** [comment]
> Same bug reappeared on my ubuntu machines. Firefox headless starts reporting a couple of non-critical issues:
> 
> ```
> firefox --headless
> /usr/bin/firefox: 12: xdg-settings: not found
> *** You are running in headless mode.
> [GFX1-]: glxtest: Unable to open a connection to the X server
> [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
> ```
> 
> Not sure how critical this is. Any help would be appreciated.

I met with the same error. @tombh
