### ISSUE TITLE
docker - panic: Config file error: open /app/.config/browsh/config.toml: permission denied

### ISSUE THREAD

**Issue by kuntau** [browsh-org/browsh#323]
First time using browsh & docker.. sorry if I missed something obvious

Installed using `sudo docker pull browsh/browsh` on `Ubuntu 20.04`

```sh
❯ sudo docker run browsh/browsh
panic: Config file error: open /app/.config/browsh/config.toml: permission denied


goroutine 1 [running]:
browsh/interfacer/src/browsh.loadConfig()
        /go-home/src/browsh/interfacer/src/browsh/config.go:95 +0x466
browsh/interfacer/src/browsh.Initialise()
        /go-home/src/browsh/interfacer/src/browsh/browsh.go:90 +0x43
browsh/interfacer/src/browsh.MainEntry()
        /go-home/src/browsh/interfacer/src/browsh/browsh.go:206 +0x23d
main.main()
        /go-home/src/browsh/interfacer/src/main.go:6 +0x20
```

**Comment by tombh** [comment]
Thanks for the issue. All I can say is that this shouldn't happen :/ Internally the docker image has all its permissions already setup correctly. The only thing I can think of is that your docker is doing something odd with its layers. Maybe try without sudo?

**Comment by kuntau** [comment]
Without sudo, docker can't run at all. I installed docker using snap, do
you think any potential problems with that?
