### ISSUE TITLE
Ubuntu x64 fresh install returns panic runtime error

### ISSUE THREAD

**Issue by sudo-monkey** [browsh-org/browsh#446]
After done fresh installations according to docs:
`$ which browsh`
`usr/bin/browsh`

when run, `browsh` || `browsh --debug`
1. blank screen for few seconds
2. Sorry I had to post a screenshot since I can't find a way to copy the error in text form
![2022-10-03_14-53](https://user-images.githubusercontent.com/83343556/193517279-2b0bb49b-495d-4bbf-987e-378714eb58ce.png)

when run, `browsh --http-server-mode`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4bba59]

goroutine 18 [running]:
os.(*Process).signal(0x46?, {0x94f4d8?, 0xb1ad30?})
	/opt/hostedtoolcache/go/1.18.4/x64/src/os/exec_unix.go:63 +0x39
os.(*Process).Signal(...)
	/opt/hostedtoolcache/go/1.18.4/x64/src/os/exec.go:138
os.(*Process).kill(...)
	/opt/hostedtoolcache/go/1.18.4/x64/src/os/exec_posix.go:67
os.(*Process).Kill(0xc0000e6000?)
	/opt/hostedtoolcache/go/1.18.4/x64/src/os/exec.go:123 +0x27
github.com/browsh-org/browsh/interfacer/src/browsh.startHeadlessFirefox()
	/home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:92 +0x4ad
created by github.com/browsh-org/browsh/interfacer/src/browsh.setupFirefox
	/home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:303 +0x25
```

**Comment by tombh** [comment]
Is there no contents of `./debug.log`? I think you've only posted STDOUT right?

**Comment by sudo-monkey** [comment]
> Is there no contents of `./debug.log`? I think you've only posted STDOUT right?

Hi,

Yes. Sorry, this is my first bug report ever.

Here is output from debug.log

`Looking in /home/monkey/.config/browsh/config.toml for config.
Starting Firefox in headless mode
Attempting to connect to Firefox Marionette
Using Firefox at: /usr/bin/firefox
Using default profile at: /home/monkey/.config/browsh/firefox_profile`

**Comment by sudo-monkey** [comment]
So I got this followings error
`Failed to load module “xapp-gtk3-module”`
`Failed to load module "Canberra-gtk-module"`
`ATTENTION: default value of option mesa_glthread overridden by environment.`

subsequently a popup box 

`Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.`

So I found out that it caused by snap Firefox so I followed and installed the ppa apt version:
[https://askubuntu.com/questions/1409575/ubuntu-22-04-lts-starting-firefox-through-terminal-error-cannot-change-mount](url)

Now if I run
`/usr/bin/firefox --profile /home/monkey/.config/browsh/firefox_profile`

I got
`ATTENTION: default value of option mesa_glthread overridden by environment.`
and the popup box
`Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.`

Extra steps:
- I have killed the process and still yielding to same error.
- I have permissioned {home}/.mozilla for read/delete files as well.

**Comment by tombh** [comment]
Getting Firefox running isn't strictly an issue for this project I'm afraid. Unless of course Brwosh caused the problem in the first place. Perhaps there are Ubuntu forums that can help?

**Comment by fny** [comment]
I'm having the same issue and Firefox is running perfectly fine. Debug log:

```
Looking in /home/dheconnect/.config/browsh/config.toml for config.
Starting Firefox in headless mode
Attempting to connect to Firefox Marionette
Using Firefox at: /usr/bin/firefox
Using default profile at: /home/dheconnect/.config/browsh/firefox_profile
```

**Comment by tombh** [comment]
Could you post the output of `firefox --profile $HOME/.config/browsh/firefox_profile` please?

**Comment by fny** [comment]
There's no output. It just runs.

**Comment by arbitrary-dev** [comment]
Same problem...
```
$ firefox --profile $HOME/.config/browsh/firefox_profile
/usr/bin/firefox: 12: xdg-settings: not found
mkdir: cannot create directory '/run/user/1002': Permission denied
Error: no DISPLAY environment variable specified
```

**Comment by tombh** [comment]
`/run/user/1002` doesn't sound like something that would happen in a normal install. Are you running it in Docker?

**Comment by arbitrary-dev** [comment]
I'm running it in a virtual private server. The docker image linked in the docs is working fine though.

**Comment by arbitrary-dev** [comment]
But why docker image is working fine on the same virtual server though? 🤔

**Comment by tombh** [comment]
The Docker image already contains Xfvb

**Comment by kalloc** [comment]
I have the same problem on latest LTS Ubuntu.
Installing Xvfb is not the solution.
Ready to make any analyzes that helps to find proper solution.

**Comment by kalloc** [comment]
--http-server-mode works well

**Comment by kalloc** [comment]
got the error in message:
```
[4160938.495613] audit: type=1400 audit(1671487379.507:1733): apparmor="DENIED" operation="mknod" profile="snap.firefox.firefox" name="/home/y/.config/browsh/firefox_profile/Telemetry.FailedProfileLocks.txt" pid=121692 comm="firefox" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

**Comment by kalloc** [comment]
I think you need an apparmor profile for Firefox

**Comment by tombh** [comment]
I don't think Browsh supports the Snap version of Firefox

**Comment by kalloc** [comment]
sure, this helps.

**Comment by fahran** [comment]
@tombh & @sudo-monkey managed to get me to the stage of having a workaround :tada: 

Browsh did not work with snap firefox for me, but worked with apt.
I followed these steps: https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

debug.log contents were sadly not particularly informative:
```
Looking in /home/fahran/.config/browsh/config.toml for config.
Starting Firefox in headless mode
Attempting to connect to Firefox Marionette
Using Firefox at: /usr/bin/firefox
Using default profile at: /home/fahran/.config/browsh/firefox_profile
```

**Comment by ioogithub** [comment]
Is it possible to run this app at all on ubuntu 22.04? I am getting the same kernel panic and then a messed up terminal on a new install. Ive tried a few of the suggestions in this tread but nothing seem to work.

I see 8 out of the last 10 issues opened have not been answered. Am I wasting my time on an abandoned project?

**Comment by profMastermind** [comment]
Solved this problem on Ubuntu 24.04, removed snap firefox, installed firefox from apt ppa and installed browsh..
Linked firefox profile to browsh config
ln -s ~/.mozilla/firefox ~/.config/browsh/firefox_profile
## for unknown reason $firefox --profile #is failing

![image](https://github.com/user-attachments/assets/6f564afd-981c-4c58-93bc-d6284da5d018)

**Comment by jerubball** [comment]
Same as #509,

Here is solution I found:

Modify your config file located at `~/.config/browsh/config.toml` and add following line to **[firefox]** section

```
path = "/snap/firefox/current/usr/lib/firefox/firefox"
```
