### ISSUE TITLE
browsh crashes in iTerm2 on MacOS

### ISSUE THREAD

**Issue by nabeelomer** [browsh-org/browsh#94]
<img width="1528" alt="screen shot 2018-07-10 at 8 03 49 pm" src="https://user-images.githubusercontent.com/11234616/42517110-9a7df9c6-847c-11e8-854d-ab030e93ef5a.png">

**Comment by jcelliott** [comment]
I'm also seeing a crash on MacOS:

```
panic: runtime error: invalid memory address or nil pointer dereference
          [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10a73fe]

goroutine 10 [running]:
os.(*Process).signal(0x0, 0x13d6ac0, 0x152c2b0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(0x0, 0x13d6ac0, 0x152c2b0, 0xc42005be90, 0x18)
       /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x3f
os.(*Process).kill(0x0, 0xc42071a1a8, 0xc42005be90)
       /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x43
os.(*Process).Kill(0x0, 0x4, 0x4)
       /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x2b
browsh/interfacer/src/browsh.startHeadlessFirefox()
       /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:84 +0x365
created by browsh/interfacer/src/browsh.setupFirefox
       /home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:252 +0x35
```

**Comment by lyletagawa** [comment]
Same (along with `v1.2.2`). However, the binary release of `v1.2.1` works for me on macOS/iTerm2

**Comment by tombh** [comment]
As of v1.3.2 this should be fixed. This version is also deployed to `ssh brow.sh`, so you should be able to test the fix there as well. Please let me know if you still have problems.

**Comment by tombh** [comment]
Oh wait, @jcelliott your error is different, can you send the output of `./debug.log` after running with the `-debug` flag.

**Comment by puppycodes** [comment]
OSX High Sierra 10.13.5 (17F77)

@tombh working for me now via ssh brow.sh,  but the binary is still failing with this output: 

```

                                      os.(*Process).signal(0x0, 0x13d72c0, 0x152d2b0, 0x0, 0x0)
                /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_unix.go:56 +0x2e
              os.(*Process).Signal(0x0, 0x13d72c0, 0x152d2b0, 0xc42022fe90, 0x18)
 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x3f
  os.(*Process).kill(0x0, 0xc420076928, 0xc42022fe90)
                                                     	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x43
                                                       os.(*Process).Kill(0x0, 0x4, 0x4)
        	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x2b
          browsh/interfacer/src/browsh.startHeadlessFirefox()
                                                             	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:85 +0x36a
                                                         created by browsh/interfacer/src/browsh.setupFirefox
                             	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:303 +0x35
```

debug.log only outputs:

```
Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Using default profile at: /Users/alice/Library/Application Support/browsh/firefox_profile
```

**Comment by jcelliott** [comment]
Mine is working now (with the older version I was using as well as the latest version). The only thing I did was restart my computer, so I'm wondering if it had to do with firefox updating or restarting. Thanks for looking into it.

**Comment by tombh** [comment]
Thanks @jcelliott.

@puppycodes So it looks like you have the same error as @jcelliott, I'm at a loss as to what it could be about. The only thing I can think of is to try starting headless Firefox manually just to see if it has any relevant output: `firefox --marionette --headless`. Also, it might be interesting to try connecting to that manually started instance with `browsh --use-existing-ff`.

**Comment by metaweta** [comment]
I'm getting this with 1.8.0:
```
Last login: Mon May  4 08:48:13 on ttys009
[Tlon:stay@mbp ~]$ brew remove browsh
Uninstalling /opt/homebrew/Cellar/browsh/1.8.0... (4 files, 8MB)
[Tlon:stay@mbp ~]$ brew install browsh
==> Fetching downloads for: browsh
✔︎ Formula browsh (1.8.0)                                                                                                    Verified      3.5MB/  3.5MB
==> Installing browsh from browsh-org/browsh
==> Caveats
You need Firefox 57 or newer to run Browsh
==> Summary
🍺  /opt/homebrew/Cellar/browsh/1.8.0: 4 files, 8MB, built in 0 seconds
==> Running `brew cleanup browsh`...
Disable this behaviour by setting `HOMEBREW_NO_INSTALL_CLEANUP=1`.
Hide these hints with `HOMEBREW_NO_ENV_HINTS=1` (see `man brew`).
[Tlon:stay@mbp ~]$ browsh

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103089b20]
goroutine 22 [running]:
os.(*Process).signal(0x0?, {0x1034ddfd8?, 0x1036a1038?})
                     /opt/hostedtoolcache/go/1.18.4/x64/src/os/exec_unix.go:63 +0x30
os.(*Process).Signal(...)
                     /opt/hostedtoolcache/go/1.18.4/x64/src/os/exec.go:138
os.(*Process).kill(...)
                     /opt/hostedtoolcache/go/1.18.4/x64/src/os/exec_posix.go:67
os.(*Process).Kill(0x0?)
                     /opt/hostedtoolcache/go/1.18.4/x64/src/os/exec.go:123 +0x30
github.com/browsh-org/browsh/interfacer/src/browsh.startHeadlessFirefox()
                     /home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:92 +0x434
created by github.com/browsh-org/browsh/interfacer/src/browsh.setupFirefox
                     /home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:303 +0x28
```

I also got a message once about macos preventing terminal from making changes to my system, but don't see anywhere in the Security & Privacy panel to allow browsh to do that.
